### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by ahyattdev** [shokunin000/te120#3]
I have compiled the binaries necessary for running this game on Mac and packaged them so that they are all that needs to be uploaded to a Mac depot. 

[Link to a ZIP of it on Google Drive](https://drive.google.com/open?id=0B0DeswTE4j_9aC0zbW5QaG1DUW8)

I included all the equivalent files that the Linux depot does and have tested this by overlaying it on a Windows installation of TE120 and it runs fine on macOS. 

Everything was done as a release build in Xcode.

**Comment by shokunin000** [comment]
This is awesome Andrew! Good work! How did the game run?

Basically the limiting factor here is my time, between family & work I haven't had much time for personal work. To get this setup on steam is also a bit more complicated than it sounds and requires some beta testing. I definitely would like to get this setup. I'll keep you updated!

**Comment by ahyattdev** [comment]
It ran without issue. Let me know if you need a beta tester or other help. Great game!

**Comment by ahyattdev** [comment]
Hey man I totally understand if you are still busy, but if there is any way to expedite this let me know. If you need to remote into a real Mac for this I have you covered.

**Comment by ahyattdev** [comment]
Any movement? Still interested in this game.

**Comment by shokunin000** [comment]
Hello Andrew,

My apologies for the delayed response. I don't check this email too often these days. To be honest I don't have all the tools setup anymore for uploads to steam. But in addition to steam backend work I really would need to double check the code changes and compile for security reasons. Unfortunately it just doesn't look like something I can do.

But what you have done is awesome. I want a Mac version to be realized as well. Would it be possible to instead post a link to a GitHub repo with your code & compiled binaries with step by step instructions on how to run on Mac?

This news would appear on the TE120 store page. Even if it ends up being a lot of steps I think it's better than this never getting revealed to the community. Thoughts?

**Comment by ahyattdev** [comment]
@shokunin000 no worries, sounds good. I am preparing a list of instructions. Is there anything preventing the stuff in `master` from being merged with `release`?

**Comment by ahyattdev** [comment]
@shokunin000 here are the instructions

These instructions are operating on the `master` branch of my fork of the source. I merged it with `release` and made a few minor changes to get it to compile on macOS. 

1) Install steam
2) Download Source SDK Base 2013 Singleplayer
3) Install Xcode from the App Store (Or download from the website)
4) Run `xcode-select --install`
5) Download openssl 1.0.2 [here](https://www.openssl.org/source/)
6) Run `./Confiure darwin-i386-cc; make` in the source root of openssl
7) Run `cp libcrypto.a <te120 source root>/lib/common/osx32`
8) Run `mkdir common/osx32; cp /usr/local/opt/openssl/lib/libcrypto.a common/osx32`
9) Run `./creategameprojects`
10) Open `games.xcodeproj`
11) Select `client (episodic)` in the scheme menu (by the run button)
12) Click "Archive" in the "Product" menu
13) Select `client (episodic)` in the scheme menu (by the run button)
14) Click "Archive" in the "Product" menu
15) Go to the Window menu and select Organizer
16) Select Export... and export the Built Products for client and server

Once you have `client.dylib` and `server.dylib`:
1) Navigate to `~/Library/Application Support/Steam/steamapps/common/Source SDK Base 2013 Singleplayer`
2) Copy the `te120` game files folder (contains `bin`, `cfg`, `maps`, etc) into the Source SDK folder
3) Put `client.dylib` and `server.dylib` in `te120/bin`
4) Edit the launch options of the SDK in Steam to be `-game te120`
5) Launch the Source SDK in Steam and TE120 will launch

If you need help with creating a depot to distribute this game let me know. 

I hope that these instructions are clear.

**Comment by shokunin000** [comment]
Hello,

Thanks for putting these instructions together.

"Is there anything preventing the stuff in master from being merged with
release?"
Honestly it's been so long I'm not sure what's in the branch. If I recall
correctly it was just to be safe to have new code separate from shipped
code, so some of it may have never been moved back to released version of
TE120.

Do you have the source code for the mac version posted somewhere? Sorry,
thought you shared that already but digging through these e-mails I'm not
able to find any links. Is it posted on github?

Does the mac version require Source SDK Base 2013? If so do you know what
files are missing in from TE120 that are in the source sdk base? I'm
curious if it is possible to zip up all the binaries, and whatever files
are needed from the source sdk, to extract onto TE120 to get this working
for mac.

Thanks!

**Comment by shokunin000** [comment]
Do you know how to download TE120 files from steam for mac?

**Comment by ahyattdev** [comment]
@shokunin000 the code that I was able to compile is located in the master branch of my fork of the repository. 

https://github.com/ahyattdev/te120/tree/master

Once you download Source SDK 2013 Singleplayer you can find it's files in your Library folder. 

You can run `open "/Users/andrewhyatt/Library/Application Support/Steam/steamapps/common/Source SDK Base 2013 Singleplayer"/` in order to go directly to it. 

If you were to zip of the files specific to the Mac version of the game, the files you need from the SDK (the folder opened by the `open` command mentioned above) are as follows:

- Everything in the `bin` folder
- `hl2.sh`
- `hl2_osx`
- `te120/bin/client.dylib` and `te120/bin/server.dylib`, obtained by the instructions for compiling it. 


Here is an example of the files necessary to be dropped over TE120 in order to get it to work on Mac. https://drive.google.com/file/d/0B0DeswTE4j_9aC0zbW5QaG1DUW8/view?usp=sharing

I hope this helps.

**Comment by ahyattdev** [comment]
I hope this is helpful

**Comment by ahyattdev** [comment]
closing as i no longer use macOS (went to Linux) and due to lack of response.
